openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    $ref: "./paths/pets.yaml"
  /pets/{petId}:
    $ref: "./paths/pets-petId.yaml"
components:
  schemas:
    Pet:
      $ref: "./schemas/Pet.yaml"
    Pets:
      $ref: "./schemas/Pets.yaml"
    Error:
      $ref: "./schemas/Error.yaml"
